# This file is a template, and might need editing before it works on your project.
# Read more about this script on this blog post https://about.gitlab.com/2018/10/24/setting-up-gitlab-ci-for-android-projects/, by Jason Lenny
# If you are interested in using Android with FastLane for publishing take a look at the Android-Fastlane template.

image: miadmin_android29:latest

variables:
  ANDROID_COMPILE_SDK: "29"
  ANDROID_BUILD_TOOLS: "29.0.2"
  ANDROID_SDK_TOOLS: "4333796"

before_script:
  - apt-get --quiet update --yes
  - apt-get --quiet install --yes wget tar unzip lib32stdc++6 lib32z1
  - wget --quiet --output-document=android-sdk.zip https://dl.google.com/android/repository/sdk-tools-linux-${ANDROID_SDK_TOOLS}.zip
  - unzip -d android-sdk-linux android-sdk.zip
  - echo y | android-sdk-linux/tools/bin/sdkmanager "platforms;android-${ANDROID_COMPILE_SDK}" >/dev/null
  - echo y | android-sdk-linux/tools/bin/sdkmanager "platform-tools" >/dev/null
  - echo y | android-sdk-linux/tools/bin/sdkmanager "build-tools;${ANDROID_BUILD_TOOLS}" >/dev/null
  - export ANDROID_HOME=$PWD/android-sdk-linux
  - export PATH=$PATH:$PWD/android-sdk-linux/platform-tools/

lintDebug:
  stage: build
  script:
    - cd exercise_1/code
    - ./gradlew -Pci --console=plain :app:lintDebug -PbuildDir=lint
    - cd ../../exercise_2/code
    - ./gradlew -Pci --console=plain :app:lintDebug -PbuildDir=lint
    - cd ../../exercise_3/code
    - ./gradlew -Pci --console=plain :android:lintDebug -PbuildDir=lint

assembleDebug:
  stage: build
  script:
    - cd exercise_1/code
    - ./gradlew assembleDebug
    - cd ../../exercise_2/code
    - ./gradlew assembleDebug
    - cd ../../exercise_3/code
    - ./gradlew assembleDebug

debugTests:
  stage: test
  script:
    - cd exercise_1/code
    - ./gradlew -Pci --console=plain :app:testDebug
    - cd ../../exercise_2/code
    - ./gradlew -Pci --console=plain :app:testDebug
    - cd ../../exercise_3/code
    - ./gradlew -Pci --console=plain :android:testDebug
