@startuml
!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/release/1-0/C4_Container.puml
!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/release/1-0/C4.puml
!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/release/1-0/C4_Component.puml
!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/release/1-0/C4_Context.puml

Person(user, "User")
System_Boundary(marauder_map, "Marauder Map") {
    Container(mobileApp, "Mobile App", "Java MVVM", "Provides a Map to show users nearby")
    Container(webApplication, "Web Application", "Java MVC", "Delivers the information about other users nearby")
    Container(restApi, "Rest API", "Java MVVM", "Provides Map functionality via JSON/HTTPS API")
}
Rel(user, webApplication, "uses", "HTTPS")
Rel(user, mobileApp, "uses")
Rel(webApplication, mobileApp, "delivers")
Rel(mobileApp, restApi, "uses", "JSON/HTTPS")

@enduml